spring:
#    datasource:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: org.postgresql.Driver
#        url: jdbc:postgresql://localhost:5432/roboAnalise
#        username: postgres
#        password: postgres

    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://192.168.15.12:5432/roboAnalise
        username: postgres
        password: postgres